"""ClusterChain Protocol Implementation

Synthesis of LEACH-style clustering and PEGASIS-style chain relaying:
- Cluster heads elected by residual-energy AND distance-to-sink weighted score
  (fixes LEACH's random CH election that wastes energy on far/multipath hops)
- Only the ~k cluster heads form a greedy chain to the sink
  (fixes PEGASIS's 100-node chain: every node relays, ~100-hop delay)
- Chain terminus (the node that does the single sink hop) rotates by residual
  energy each round (fixes PEGASIS's permanent leader hotspot)

PDR is defined uniformly across all protocols as:
    packets delivered to sink / packets generated by alive source nodes
so the 3-way comparison is apples-to-apples.
"""
import random
import math
import numpy as np
from dataclasses import dataclass, field
from typing import List, Optional, Set
from energy import tx_energy, rx_energy, da_energy, PACKET_SIZE, E_ELEC, E_FS, E_MP


def optimal_k(n_alive: int) -> int:
    """Analytically-derived energy-optimal chain length k* for n_alive nodes.

    Minimises the per-round energy E(k) from the Heinzelman first-order model
    (see derivation.md). The minimum sits at a small k (3-4 for typical N)
    because the expensive multipath sink hop is shared across all nodes and the
    two distance-squared terms both fall with k up to that point. Used to set
    the cluster-head count adaptively as nodes die.
    """
    if n_alive <= 3:
        return max(1, n_alive - 1)
    a = 100.0 / (2 * (3.141592653589793 ** 0.5))
    b = 50.0
    D = 125.0
    L = PACKET_SIZE
    e_rx = L * E_ELEC
    e_da = L * 5e-9
    e_sink = L * E_ELEC + L * E_MP * (D ** 4)

    def e_round(k):
        k = max(1, min(k, n_alive))
        d_m2 = a * a / k
        e_member = (n_alive - k) * (L * E_ELEC + L * E_FS * d_m2)
        e_ch_rx = n_alive * e_rx
        e_da_tot = n_alive * e_da
        d_c2 = b * b / (k * k)
        e_chain = (k - 1) * (L * E_ELEC + L * E_FS * d_c2)
        e_chain_rx = k * e_rx
        return e_member + e_ch_rx + e_da_tot + e_chain + e_chain_rx + e_sink

    return min(range(1, n_alive + 1), key=e_round)


@dataclass
class CCNode:
    id: int
    x: float
    y: float
    energy: float = 0.5
    alive: bool = True
    is_ch: bool = False
    ch_id: Optional[int] = None
    chain_next: Optional[int] = None
    is_terminus: bool = False
    score: float = 0.0  # transient: cluster-head election score for the round

    def distance_to(self, other: 'CCNode') -> float:
        return math.hypot(self.x - other.x, self.y - other.y)

    def consume(self, amount: float) -> bool:
        self.energy -= amount
        if self.energy <= 0:
            self.alive = False
            self.energy = 0
            return True
        return False


class ClusterChain:
    def __init__(
        self,
        n_nodes: int = 100,
        field_x: float = 100,
        field_y: float = 100,
        sink_x: float = 50,
        sink_y: float = 175,
        initial_energy: float = 0.5,
        n_ch: int = 5,
        w_energy: float = 0.7,
        ch_mode: str = 'sink',
        terminus: str = 'energy',
        adaptive_k: bool = True,
    ):
        self.n = n_nodes
        self.field_x = field_x
        self.field_y = field_y
        self.sink = CCNode(-1, sink_x, sink_y, energy=float('inf'))
        self.initial_energy = initial_energy
        self.n_ch = max(1, min(n_ch, n_nodes))
        self.w_energy = w_energy
        self.ch_mode = ch_mode  # 'sink' | 'spread' | 'coverage' | 'dense'
        self.terminus = terminus  # 'energy' | 'sink'
        self.adaptive_k = adaptive_k  # recompute k* from energy model as nodes die
        self.round = 0
        self.alive_count = n_nodes
        self.history = []  # (round, alive, total_energy, pdr, avg_delay, packets_sent, packets_received)

        self.nodes = [
            CCNode(i, random.uniform(0, field_x), random.uniform(0, field_y), initial_energy)
            for i in range(n_nodes)
        ]

    # ---- setup phase (runs every round) ----
    def _elect_cluster_heads(self):
        """Pick top-n_ch nodes by a strategy that balances energy and placement.

        - 'sink'    : favour high residual energy AND proximity to sink
        - 'spread'  : favour high residual energy AND proximity to field centre
                      (even field coverage => short member->CH hops)
        - 'coverage': greedy max-min-distance coverage, energy-weighted
                      (first seed = highest-energy node, then pick the alive node
                       that maximises its distance to already-chosen CHs, weighted
                       by its normalised energy)
        """
        alive = [n for n in self.nodes if n.alive]
        if not alive:
            return
        avg_e = float(np.mean([n.energy for n in alive]))
        max_d_sink = max(n.distance_to(self.sink) for n in alive) or 1.0
        cx, cy = self.field_x / 2.0, self.field_y / 2.0

        for n in self.nodes:
            n.is_ch = False
            n.ch_id = None

        if self.ch_mode == 'coverage':
            chosen = []
            # seed with highest-energy alive node
            first = max(alive, key=lambda n: n.energy)
            chosen.append(first)
            while len(chosen) < self.n_ch:
                best, best_v = None, -1.0
                for n in alive:
                    if n in chosen:
                        continue
                    e_norm = n.energy / avg_e if avg_e > 0 else 0.0
                    min_d = min(n.distance_to(c) for c in chosen)
                    v = self.w_energy * e_norm + (1 - self.w_energy) * (min_d / max_d_sink)
                    if v > best_v:
                        best_v, best = v, n
                if best is None:
                    break
                chosen.append(best)
            for n in chosen:
                n.is_ch = True
            return

        for n in alive:
            e_norm = n.energy / avg_e if avg_e > 0 else 0.0
            if self.ch_mode == 'spread':
                prox = 1.0 - math.hypot(n.x - cx, n.y - cy) / (math.hypot(cx, cy) or 1.0)
            else:  # 'sink'
                prox = 1.0 - n.distance_to(self.sink) / max_d_sink
            n.score = self.w_energy * e_norm + (1 - self.w_energy) * prox

        alive_sorted = sorted(alive, key=lambda n: n.score, reverse=True)
        for n in alive_sorted[:self.n_ch]:
            n.is_ch = True

    def _form_clusters(self):
        chs = [n for n in self.nodes if n.alive and n.is_ch]
        if not chs:
            alive = [n for n in self.nodes if n.alive]
            if alive:
                max_node = max(alive, key=lambda n: n.energy)
                max_node.is_ch = True
                chs = [max_node]
        for n in self.nodes:
            if n.alive and not n.is_ch:
                n.ch_id = min(chs, key=lambda ch: n.distance_to(ch)).id

    def _build_ch_chain(self):
        """Form the relay chain among cluster heads and pick the terminus.

        ch_mode controls cluster-head placement; the chain is always built as a
        greedy nearest-neighbour tour over the alive CH set, terminated at the
        highest-residual-energy CH (rotated each round to avoid a leader hotspot).

        For ch_mode == 'dense' the chain is built over ALL alive nodes (PEGASIS
        style, shortest possible hops) but the terminus is still rotated by
        residual energy, which removes PEGASIS's fixed-leader hotspot.
        """
        for n in self.nodes:
            n.chain_next = None
            n.is_terminus = False

        if self.ch_mode == 'dense':
            pool = [n for n in self.nodes if n.alive]
        else:
            pool = [n for n in self.nodes if n.alive and n.is_ch]
        if not pool:
            return
        if len(pool) == 1:
            pool[0].is_terminus = True
            return

        terminus = max(pool, key=lambda n: n.energy)
        if self.terminus == 'sink':
            # terminate at the node that best balances high residual energy with
            # proximity to the sink, minimising the single expensive multipath hop
            max_e = max(n.energy for n in pool) or 1.0
            terminus = max(
                pool,
                key=lambda n: (n.energy / max_e, -n.distance_to(self.sink)),
            )
        others = [c for c in pool if c is not terminus]

        unvisited = set(c.id for c in others)
        path = [terminus]
        current = terminus
        while unvisited:
            nxt = min(
                (c for c in others if c.id in unvisited),
                key=lambda c: current.distance_to(c),
            )
            current.chain_next = nxt.id
            path.append(nxt)
            unvisited.discard(nxt.id)
            current = nxt
        rev = list(reversed(path))
        for i, c in enumerate(rev):
            c.chain_next = rev[i + 1].id if i + 1 < len(rev) else None
        terminus.is_terminus = True

    # ---- transmission phase ----
    def _transmit_round(self) -> dict:
        """One round of data transmission. PDR = source nodes whose data reached
        the sink / total alive source nodes (consistent across all protocols).

        Two logical forwarding stages:
          1) member -> CH  (ClusterChain with n_ch < n: every non-CH node sends to
             its nearest CH in a single short free-space hop)
          2) chain relay  (CH chain, or the full dense chain in 'dense' mode):
             data flows along the greedy chain to the rotated energy-rich terminus,
             which does the single sink hop.
        The terminus rotates by residual energy each round, so no node is the
        permanent long-haul leader (fixes PEGASIS's leader hotspot).
        """
        alive = [n for n in self.nodes if n.alive]
        if not alive:
            return {'tx': 0, 'rx': 0, 'sent': 0, 'received': 0, 'delay': 0}

        sent = len(alive)
        delivered = {n.id for n in alive}
        total_tx = 0.0
        total_rx = 0.0
        delays = []

        members = {n.id: [] for n in alive if n.is_ch}
        for n in alive:
            if not n.is_ch and n.ch_id is not None:
                members.setdefault(n.ch_id, []).append(n.id)

        # Stage 1: member -> CH (skip in dense mode; every node IS on the chain)
        if self.ch_mode != 'dense':
            for n in alive:
                if n.is_ch or n.ch_id is None:
                    continue
                ch = next((c for c in alive if c.id == n.ch_id), None)
                if ch is None or not ch.alive:
                    continue
                d = n.distance_to(ch)
                if n.consume(tx_energy(d)):
                    delivered.discard(n.id)
                    continue
                if ch.consume(rx_energy() + da_energy()):
                    for m in members.get(ch.id, []):
                        delivered.discard(m)
                    delivered.discard(ch.id)
                    continue
                total_tx += tx_energy(d)
                total_rx += rx_energy() + da_energy()

        # Stage 2: chain relay (CH chain, or full dense chain)
        chain_nodes = [c for c in alive if c.chain_next is not None or c.is_terminus]
        for c in chain_nodes:
            if c.chain_next is None:  # terminus -> handled below
                continue
            nxt = next((x for x in alive if x.id == c.chain_next), None)
            if nxt is None or not nxt.alive:
                delivered.discard(c.id)
                continue
            d = c.distance_to(nxt)
            if c.consume(tx_energy(d)):
                delivered.discard(c.id)
                continue
            if nxt.consume(rx_energy() + da_energy()):
                delivered.discard(nxt.id)
                continue
            total_tx += tx_energy(d)
            total_rx += rx_energy() + da_energy()

        # terminus -> sink
        terminus = next((c for c in alive if c.is_terminus), None)
        if terminus:
            d = terminus.distance_to(self.sink)
            if terminus.consume(tx_energy(d)):
                delivered.clear()
            else:
                total_tx += tx_energy(d)
                delays.append(len(chain_nodes))

        return {
            'tx': total_tx,
            'rx': total_rx,
            'sent': sent,
            'received': len(delivered),
            'delay': np.mean(delays) if delays else 0,
        }

    def step(self) -> dict:
        self.round += 1
        if self.adaptive_k and self.ch_mode != 'dense':
            self.n_ch = optimal_k(self.alive_count)
        self._elect_cluster_heads()
        self._form_clusters()
        self._build_ch_chain()
        m = self._transmit_round()

        self.alive_count = sum(1 for n in self.nodes if n.alive)
        pdr = m['received'] / max(1, m['sent'])

        self.history.append((
            self.round,
            self.alive_count,
            m['tx'] + m['rx'],
            pdr,
            m['delay'],
            m['sent'],
            m['received'],
        ))
        return {
            'round': self.round,
            'alive': self.alive_count,
            'pdr': pdr,
            'delay': m['delay'],
            'energy': m['tx'] + m['rx'],
        }

    def run(self, max_rounds: int = 2000) -> List[tuple]:
        while self.alive_count > 0 and self.round < max_rounds:
            self.step()
        return self.history
